# Generated by Django 5.2.15 on 2026-07-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatie', '0004_conversation_deleted_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chat_videos'),
        ),
    ]
