# Generated by Django 5.2.15 on 2026-07-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatie', '0006_message_delete_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='delete_for',
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
