# Generated by Django 5.2.15 on 2026-07-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatie', '0007_remove_message_delete_for_message_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_audio'),
        ),
    ]
