# Generated by Django 5.2.15 on 2026-07-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatie', '0009_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='group_photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_photos/'),
        ),
    ]
