# Generated by Django 5.2.15 on 2026-08-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatie', '0011_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='call_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='call_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='BlockedUser',
        ),
    ]
